### PR TITLE
MBV Property Based Testing -- Do Not Merge

### PR DESCRIPTION
**Pull request by Christewart**
Since this seems to be the 'official' repo for `OP_MERKLEBRANCHVERIFY` i'm opening this pull request here.

--

This pull request tests `merkle-branch-verify` [BIP 116](https://github.com/bitcoin/bips/blob/master/bip-0116.mediawiki) with property based testing. 

This pull request builds off of work I have done in [#8469](https://github.com/bitcoin/bitcoin/pull/8469) on the main bitcoin repo. Unfortunately this pull request shows *all* of the changes of that pull along with ones I have made to test MBV. 

The main files for relevant for testing MBV are 

- [merkle_properties.cpp](https://github.com/Christewart/bitcoin/blob/merkle-branch-verify-pbt/src/test/merkle_properties.cpp)
- [merkle_gen.h](https://github.com/Christewart/bitcoin/blob/merkle-branch-verify-pbt/src/test/gen/merkle_gen.h)
- [merkle_gen.cpp](https://github.com/Christewart/bitcoin/blob/merkle-branch-verify-pbt/src/test/gen/merkle_gen.cpp)

The `_gen` suffix is used for files used to generate test data structures relevant to MBV -- like a `MerkleLink`. The `_properties.cpp` suffix is the *actual* invariants that I am specifying should hold true.

The properties I have written currently are very rudimentary -- just serialization symmetry. It appears that I have possibly found a bug in the implementation though. Here is the specific test case that fails and the inputs given to it

```
$ ./test_bitcoin --run_test=merkle_properties/merkle_proof*
Running 1 test case...
Using configuration: seed=10232596564734061118
/usr/include/rapidcheck/boost_test.h(34): fatal error: in "merkle_properties/merkle_proof_serialization": 
Falsifiable after 1 tests

std::tuple<MerkleProof>:
(<???>)

test/merkle_properties.cpp:36:
RC_ASSERT(ss.str() == ss1.str())

Expands to:
"" == "\0\0"

*** 1 failure is detected in the test module "Bitcoin Test Suite"
Some of your RapidCheck properties had failures. To reproduce these, run with:
RC_PARAMS="reproduce=BwSblJ3asV2XwJ3bwVmc0lWZz9SblJ3asV2XwJ3bvZ2XzVmcpFGbppXY0l2bu5jKbrGX8Fgj+oy2qxFfB4oPqstacxXAO6jKbrGX8FgjBAQAAAAAAAA"
```

The C++ code in this implementation is pretty foreign to me -- I'm still working on understanding it. However I felt it would be useful to share this work with the wider community to hopefully help w/ testing MBV. If you don't find this useful I can close this pull request. Otherwise I will keep updating it as I do more work on testing MBV.

### CODE REVIEW

**Comment by Christewart** [comment]
Bug 2: 

This might be related to the first bug, but I am having trouble parsing a `MerkleProof` inside of the `OP_MERKLEBRANCHVERIFY` implementation. 

I'm trying to generate a very simple merkle proof for a binary tree with two leaves. You can see the implementation of this generator [here](https://github.com/Christewart/bitcoin/blob/kallewoof-mbv/src/test/gen/merkle_gen.cpp#L8-L22). The generator creates a `MerkleProof` that proves the given `hash` is part of a 2 leaf binary tree. 

I am then taking that `MerkleProof` I generated and using it to create a `OP_MERKLEBRANCHVERIFY` script. The script is created [here](https://github.com/Christewart/bitcoin/blob/kallewoof-mbv/src/test/gen/merkle_gen.cpp#L24-L47). 

When I go to run this script through the interpreter, I keep running into this error: 
`serror: Failed to decode 3rd stack item for current opcode`

The 3rd stack item is the merkle proof. It seems odd to me that I am able to generate the `MerkleProof` just fine, but I am unable to parse it inside of `interpreter.cpp`? 

Here is the merkle proof that is causing the trouble: 

xvchProof: 010001414c085529e7cb3838fe7a00872a9af5439f77738811a40bb7dfbde03f80fdf9

The pastebin of the run: 
https://pastebin.com/fZRzzWWF

**Comment by maaku** [comment]
That proof looks wrong. It’s not a well formed tree. Specifically the second byte should not be zero.

**Comment by maaku** [comment]
My prior message was incorrect. 0b000 as a node is in fact {VERIFY, SKIP}, which is a correct well-formed two element tree. We tried reproducing this error locally but everything worked correctly. I'm not sure what the source of the error is, but it might be in your test generation code. This line is capturing a reference to a temporary return value. Is that legal?

https://github.com/Christewart/bitcoin/blob/4df11ab11f314415804a3b8cf9a2f18f513112e9/src/test/gen/merkle_gen.cpp#L13

**Comment by kallewoof** [comment]
@Christewart 

In merkle_properties.cpp, there are 2 issues:

1. You are using .str() which will try to return the byte values as a string. This may actually work but I think it will normally consider the first 0x00 as NUL termination.
2. You are reading from the data stream, which iterates it forward. You need to take the string out before >>ing from it.

E.g.
```C++
RC_BOOST_PROP(merkle_proof_serialization, (MerkleProof p)) {
  CDataStream ss(SER_NETWORK, PROTOCOL_VERSION);
  ss << p;
  std::string r1 = HexStr(ss);
  MerkleProof p1;
  ss >> p1;
  CDataStream ss1(SER_NETWORK, PROTOCOL_VERSION);
  ss1 << p1;
  RC_ASSERT(r1 == HexStr(ss1));
}
```

**Comment by Christewart** [comment]
Thanks @maaku and @kallewoof . With your guy's help I was able to get this property to pass all tests. It is a simple property right now that states that `OP_MBV` should be able to prove a hash is included in a `MerkleProof` when there are two leaves in the merkle tree. 

There are some confusing parts of the BIP which weren't intuitive to me. Maybe this is just me, maybe we should reconsider wording/design choices. For instance choosing the lower order bit to indicate `prehashed` seems strange to me. Wouldn't it be wiser to choose the most significant bit? I think we use the MSB for indicating things in other parts of the protocol? Why break convention? 
 
I'm going to work on generalizing this property for `m` hashes we want to prove inclusion of and `n` leaves (instead of just 2) in the merkle tree. Of course the `m` / `n` will be subject to script limitations.

**Comment by maaku** [comment]
Was this just a cleanup close? I recently merged MBV into tradecraft, and I forgot about this PR. Any issues with it, or should I consider merging it into my branch as well?

**Comment by kallewoof** [comment]
I didn't realize I closed somebody else's PR, and I can't seem to be able to reopen it... weird. Sorry, @Christewart :/

@maaku I don't think I have adequately reviewed this to have an opinion.

**Pull request closed without merging**
