### PR TITLE
Signet with #17037 on top

### PR DESCRIPTION
**Pull request by jtimon**
Like #16411 but with #17037 and some extra changes on top of it.

### CODE REVIEW

**Comment by carnhofdaki** [comment]
Tested ACK
Works for me. Easily rebased to current master.
I use signet and it continues the one I downloaded earlier with `signet-0.18` branch of `kallewoof`.

https://github.com/carnhofdaki/bitcoin/tree/jt-signet-2-rebased-to-master

**Comment by jtimon** [comment]
No, this doesn't work, not the last commits.
To fix the test I would need something like https://github.com/bitcoin/bitcoin/pull/17032 too so that I can configure bech32_hrp and whatever I need to make them pass.
Or alternatively change the hardcoded keys or generate them dynamically.
As it is right now, it breaks mining_signet.py.

**Comment by jtimon** [comment]
I mean, the default signet itself should keep working, thanks for testing that. But this PR is not meant to be merged anyway. Is more to discuss how bitcoin#17037 and signet could fit together.

**Comment by carnhofdaki** [comment]
> I mean, the default signet itself should keep working, thanks for testing that. But this PR is not meant to be merged anyway. Is more to discuss how [bitcoin#17037](https://github.com/bitcoin/bitcoin/pull/17037) and signet could fit together.

Ah, Thanks. I did not try mining my own signet yet. Will do.

**Comment by carnhofdaki** [comment]
@jtimon Acutally custom signet does not work for me even on c584956573b553f33771b7d853e2ccf8f033d29a (currently HEAD of kallewoof/signet), i.e. without any patches on top.

**Comment by jtimon** [comment]
Well, the custom signet should not be done with -signet=1 anymore but with
-chain=anyname.

**Comment by carnhofdaki** [comment]
@jtimon Thank you! I will try it momentarily!

**Comment by carnhofdaki** [comment]
On e32b8257e877767d737fd4a7757f666ce85ee675 ([jtimon/bitcoin@jt-signet-2](https://github.com/jtimon/bitcoin/tree/jt-signet-2)) I get following when I try to `grindblock`:

```
error code: -8
error message:
Parse error decoding block $SCRIPT
```

Full reproduction script is (while `bitcoind -signet` is running):

```
#!/bin/sh

cli(){ bitcoin-cli -signet $*; }

ADDR=$(cli getnewaddress "" bech32)
PUBKEY=$(cli getaddressinfo $ADDR | jq -r .pubkey)
LEN=$(printf $PUBKEY | wc -c)
LENHEX=$(echo "obase=16; $LEN" | bc)
SCRIPT=$(echo 51${LENHEX}${PUBKEY}51ae)
cli grindblock $SCRIPT
```

Edit: simplify the reproduction script

**Comment by kallewoof** [comment]
@carnhofdaki I could be wrong here, but shouldn't you use `-chain=anyname` in the `bitcoin-cli` call as well? (You are doing `bitcoin-cli -signet $*` -- as a sidenote, you probably want `"$@"` instead of `$*` as it [properly deals with quotes](https://unix.stackexchange.com/questions/41571/what-is-the-difference-between-and))

**Comment by carnhofdaki** [comment]
@kallewoof Thank you for comments!

I actually tried to simplify the script so it was made of less and only significant lines up to the line which did not work for me. And according to [the signet article in bitcoin.it wiki](https://en.bitcoin.it/wiki/Signet#Defining_the_block_script) the `grindblock` command is run with `-signet` (white appropriate daemon is running, before stopping it).

This pull request is about signet+#17037 on top but the documentation on bitcoin wiki (which copes with vanilla signet, actually [`signet-0.18` branch is mentioned in the example](https://en.bitcoin.it/wiki/Signet#Fetch_and_compile_signet) was the only I found (apart from README in `bitcoin/contrib/signet` which explains only the scripts one by one, not the story of how to bring `signet` up).

**Pull request closed without merging**
